### ISSUE TITLE
what is function of seo_list

### ISSUE THREAD

**Issue by bq1028** [fengjinqi/website#14]
Hi, 
thank you for what you did on this good project first, 

now i have some questions, that is if there is no seo_list add to database,  the home page will not show, if del seo_list from apps/article/views.py the home page works

go to admin dashboard, only Seo can not be added, why?

thank you in advnace!

**Comment by fengjinqi** [comment]
Because I'm a little lazy. Maybe in my cognition, modules are defined first, and the database is established directly, and then the background update is done. Sorry! Bring you the same. Thank you for your advice.
