### ISSUE TITLE
?: (urls.E007) The custom handler404 view 'apps.user.views.page_not_found' does not take the correct number of arguments (request, exception).

### ISSUE THREAD

**Issue by Try-001** [fengjinqi/website#22]
apps.user.views.page_error
apps.user.views.page_not_found 
报错如下：参数错误
![image](https://user-images.githubusercontent.com/35480914/98193606-99a14c00-1f58-11eb-825d-6bdfbc394dfb.png)
![image](https://user-images.githubusercontent.com/35480914/98193627-a9b92b80-1f58-11eb-8189-473d8cfe5e54.png)

**Comment by fengjinqi** [comment]
分页缺少参数

**Comment by Try-001** [comment]
已解决
![Uploading image.png…]()

**Comment by nmanhong** [comment]
@git1e  @fengjinqi  
咋解决的啊 我也遇到了 说下咋解决的啊
