### ISSUE TITLE
非常好的项目！是否建个QQ群，持续搞起来？

### ISSUE THREAD

**Issue by children1987** [fengjinqi/website#5]
是否有个todo list？ 这样其他人也可以参与进来 @fengjinqi

**Comment by fengjinqi** [comment]
暂时还没有，目前是我个人闲时开发的，功能点有点杂乱，后续慢慢优化，会一直更新的，你可以添加这个群：180522631

**Comment by children1987** [comment]
好的，坦白讲，website 这个项目名可不怎么样



------------------ 原始邮件 ------------------
发件人: "JD Godchaux"<notifications@github.com>; 
发送时间: 2019年5月27日(星期一) 晚上6:56
收件人: "fengjinqi/website"<website@noreply.github.com>; 
抄送: "逆·寒刀"<39188043@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [fengjinqi/website] 非常好的项目！是否建个QQ群，持续搞起来？ (#5)




暂时还没有，目前是我个人闲时开发的，功能点有点杂乱，后续慢慢优化，会一直更新的，你可以添加这个群：180522631
